pipeline {
    agent any
    environment {
        CRED_ID = 'admin_pradeep_artifactory'
        ARTIFACTORY_SERVER_ID = 'http://localhost:8082/artifactory'
        ARTIFACTORY_DEPLOYER_RELEASE_REPO = 'local-repo-maven'
        ARTIFACTORY_DEPLOYER_SNAPSHOT_REPO = 'local-repo-maven'
        ARTIFACTORY_RESOLVER_RELEASE_REPO = 'local-repo-maven'
        ARTIFACTORY_RESOLVER_SNAPSHOT_REPO = 'local-repo-maven'

    }
    stages {
        stage ('Maven container config') {
            stages {
                stage ('Artifactory configuration') {
                    steps {
                        rtMavenDeployer(
                                id: "MAVEN_DEPLOYER",
                                serverId: env.ARTIFACTORY_SERVER_ID,
                                releaseRepo: env.ARTIFACTORY_DEPLOYER_RELEASE_REPO,
                                snapshotRepo: env.ARTIFACTORY_DEPLOYER_SNAPSHOT_REPO
                        )

                        rtMavenResolver(
                                id: "MAVEN_RESOLVER",
                                serverId: env.ARTIFACTORY_SERVER_ID,
                                releaseRepo: env.ARTIFACTORY_RESOLVER_RELEASE_REPO,
                                snapshotRepo: env.ARTIFACTORY_RESOLVER_SNAPSHOT_REPO
                        )
                    }
                }
                stage ('Publish BuildInfo') {
                    steps {
                        rtBuildInfo (
                                captureEnv: true
                        )
                        rtPublishBuildInfo (
                                serverId: env.ARTIFACTORY_SERVER_ID
                        )
                    }
                }
                stage('Build') {
                    steps {
                        rtMavenRun (
                                pom: 'pom.xml',
                                goals: '-B -DskipTests clean package',
                                deployerId: "MAVEN_DEPLOYER",
                                resolverId: "MAVEN_RESOLVER"
                        )
                    }
                }
            }
        }
    }
}